[build]
  command = "npm install && npm run build"
  publish = "dist"
  functions = "../backend/functions"

# Redirect API requests to the serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirect product API requests to the products function
[[redirects]]
  from = "/products/*"
  to = "/.netlify/functions/products/:splat"
  status = 200

# Redirect all other requests to the frontend app
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200