services:
  - type: web
    name: anzia-frontend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_BASE_URL
        value: https://anzia-api.onrender.com/api
      - key: VITE_IMAGEKIT_URL
        value: https://ik.imagekit.io/q5jukn457