services:
  # Backend API service
  - type: web
    name: anzia-electronics-api
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm run start:render
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        value: anziaelectronics
      - key: JWT_SECRET
        sync: false
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        value: https://ik.imagekit.io/q5jukn457

  # Frontend service
  - type: web
    name: anzia-electronics-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_BASE_URL
        value: https://anzia-electronics-api.onrender.com/api
      - key: VITE_IMAGEKIT_URL
        value: https://ik.imagekit.io/q5jukn457

  # Admin dashboard service
  - type: web
    name: anzia-electronics-admin
    env: node
    buildCommand: cd admin && npm install && npm run build
    startCommand: cd admin && npm run preview -- --port $PORT --host 0.0.0.0
    envVars:
      - key: VITE_API_BASE_URL
        value: https://anzia-electronics-api.onrender.com/api
      - key: VITE_IMAGEKIT_URL
        value: https://ik.imagekit.io/q5jukn457